# Generated by Django 3.2.4 on 2021-07-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20210702_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Bprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Sprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
