# Generated by Django 3.2.4 on 2021-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='table',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
