# Generated by Django 3.2.4 on 2021-07-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Sprice',
            field=models.IntegerField(default=0),
        ),
    ]
